name: money_input_formatter
description: Custum Monet Input Formatter
version: 0.0.1
homepage: https://github.com/RSS-Interactive/money_input_formatter.git

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  function_tree: ^0.8.12

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
